# This is a basic workflow to help you get started with Actions

name: deploy-to-github-pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          check-latest: true
      
      - name: Set up git config
        run: git config --global user.email "673643706@qq.com" & git config --global user.name "xdlrt"
      
      - name: Install hexo
        run: npm i -g hexo@6

      - name: Install dependencies
        run: yarn
      
      - name: Build
        run: hexo clean & hexo generate
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.G_T }}
          branch: master
          repository-name: xdlrt/xdlrt.github.io
          git-config-name: xdlrt
          git-config-email: 673643706@qq.com
          folder: public
